name: QT5/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup C++ environment
      uses: kurocha/setup-cpp@v1
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Qt5Gui
      run: sudo apt install ffmpeg sox mplayer libnotify-dev qt5-default qt5-qmake g++ make multimedia multimediawidgets
    - name: Qt5 Version info
      run: dpkg -l | grep qt5-default  
    - name: qmake
      run: qmake QtVsPlayer.pro
    - name: make
      run: make
